hostname: R2
loopback_ipv4: 10.255.1.2
loopback_ipv6: 2001:DB8:1::2

interfaces:
  - name: Loopback0
    ipv4: 10.255.1.2/32
    ipv6: 2001:DB8:1::2/128
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/0
    desc: R2-R3
    ipv4: 10.0.0.5/30
    ipv6: 2001:DB8:0:23::2/64
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/1
    desc: R2-R4
    ipv4: 10.0.0.13/30
    ipv6: 2001:DB8:0:24::2/64
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/2
    desc: R2-ISP2
    ipv4: 10.0.0.41/30
    ipv6: 2001:DB8:FD02::2/64

bgp:
  router_id: 10.255.1.2
  neighbors_ipv4:
    - { addr: 10.0.0.42, remote_as: 65020, edge_isp: true }
    - { addr: 10.255.1.3, remote_as: 65001, rr: true }
    - { addr: 10.255.1.4, remote_as: 65001, rr: true }
  neighbors_ipv6:
    - { addr: 2001:DB8:1::3, remote_as: 65001, rr: true }
    - { addr: 2001:DB8:1::4, remote_as: 65001, rr: true }
    - { addr: 2001:DB8:FD02::10, remote_as: 65020, edge_isp: true }
  networks_ipv4:
    - 10.20.20.1/32
    - 10.255.1.2/32
  networks_ipv6:
    - 2001:DB8:1::2/128