hostname: R3
loopback_ipv4: 10.255.1.3
loopback_ipv6: 2001:DB8:1::3

interfaces:
  - name: Loopback0
    ipv4: 10.255.1.3/32
    ipv6: 2001:DB8:1::3/128
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/0
    desc: R3-R1
    ipv4: 10.0.0.2/30
    ipv6: 2001:DB8:0:13::3/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/1
    desc: R3-R2
    ipv4: 10.0.0.6/30
    ipv6: 2001:DB8:0:23::3/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/2
    desc: R3-R4
    ipv4: 10.0.0.17/30
    ipv6: 2001:DB8:0:34::3/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/3
    desc: R3-R5
    ipv4: 10.0.0.21/30
    ipv6: 2001:DB8:0:35::3/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/4
    desc: R3-R6
    ipv4: 10.0.0.25/30
    ipv6: 2001:DB8:0:36::3/64
    ospf: true
    ospfv3: true
    mpls: true

bgp:
  router_id: 10.255.1.3
  neighbors_ipv4:
    - { addr: 10.255.1.1, remote_as: 65001, client: true }
    - { addr: 10.255.1.2, remote_as: 65001, client: true }
    - { addr: 10.255.1.5, remote_as: 65001, client: true }
    - { addr: 10.255.1.6, remote_as: 65001, client: true }
    - { addr: 10.255.1.7, remote_as: 65001, client: true }
    - { addr: 10.255.1.8, remote_as: 65001, client: true }
  neighbors_ipv6:
    - { addr: 2001:DB8:1::1, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::2, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::5, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::6, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::7, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::8, remote_as: 65001, client: true }
  networks_ipv6:
    - 2001:DB8:1::3/128
  vpn_rr: true