hostname: R4
loopback_ipv4: 10.255.1.4
loopback_ipv6: 2001:DB8:1::4

interfaces:
  - name: Loopback0
    ipv4: 10.255.1.4/32
    ipv6: 2001:DB8:1::4/128
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/0
    desc: R4-R1
    ipv4: 10.0.0.10/30
    ipv6: 2001:DB8:0:14::4/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/1
    desc: R4-R2
    ipv4: 10.0.0.14/30
    ipv6: 2001:DB8:0:24::4/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/2
    desc: R4-R3
    ipv4: 10.0.0.18/30
    ipv6: 2001:DB8:0:34::4/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/3
    desc: R4-R7
    ipv4: 10.0.0.29/30
    ipv6: 2001:DB8:0:47::4/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/4
    desc: R4-R8
    ipv4: 10.0.0.33/30
    ipv6: 2001:DB8:0:48::4/64
    ospf: true
    ospfv3: true
    mpls: true

bgp:
  router_id: 10.255.1.4

  neighbors_ipv4:
    - { addr: 10.255.1.1, remote_as: 65001, client: true }
    - { addr: 10.255.1.2, remote_as: 65001, client: true }
    - { addr: 10.255.1.5, remote_as: 65001, client: true }
    - { addr: 10.255.1.6, remote_as: 65001, client: true }
    - { addr: 10.255.1.7, remote_as: 65001, client: true }
    - { addr: 10.255.1.8, remote_as: 65001, client: true }

  neighbors_ipv6:
    - { addr: 2001:DB8:1::1, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::2, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::5, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::6, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::7, remote_as: 65001, client: true }
    - { addr: 2001:DB8:1::8, remote_as: 65001, client: true }

  networks_ipv6:
    - 2001:DB8:1::4/128

  vpn_rr: true