hostname: R5
loopback_ipv4: 10.255.1.5
loopback_ipv6: 2001:DB8:1::5

interfaces:
  - name: Loopback0
    ipv4: 10.255.1.5/32
    ipv6: 2001:DB8:1::5/128
    ospf: true
    ospfv3: true

  - name: GigabitEthernet0/3
    desc: R5-R3
    ipv4: 10.0.0.22/30
    ipv6: 2001:DB8:0:35::5/64
    ospf: true
    ospfv3: true
    mpls: true

  - name: GigabitEthernet0/2
    desc: R5-CE
    vrf: CUST-A
    ipv4: 10.10.5.1/24
    ipv6: 2001:DB8:A:5::1/64

bgp:
  router_id: 10.255.1.5
  neighbors_ipv4:
    - { addr: 10.255.1.3, remote_as: 65001, rr: true }
    - { addr: 10.255.1.4, remote_as: 65001, rr: true }
  neighbors_ipv6:
    - { addr: 2001:DB8:1::3, remote_as: 65001, rr: true }
    - { addr: 2001:DB8:1::4, remote_as: 65001, rr: true }
  vrfs:
    - name: CUST-A
      ipv4_redistribute_connected: true
      ipv6_redistribute_connected: true