all:
  children:
    edge:
      hosts:
        R1:
        R2:
    rr:
      hosts:
        R3:
        R4:
    pe:
      hosts:
        R5:
        R6:
        R7:
        R8:
    core:
      hosts:
        R3:
        R4:
        R5:
        R6:
        R7:
        R8:
    isp:
      hosts:
        R9:
        R10:
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: network_cli
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable