role: rr

rr_clients_ipv4:
  - 10.255.1.1
  - 10.255.1.2
  - 10.255.1.5
  - 10.255.1.6
  - 10.255.1.7
  - 10.255.1.8

rr_clients_ipv6:
  - 2001:DB8:1::1
  - 2001:DB8:1::2
  - 2001:DB8:1::5
  - 2001:DB8:1::6
  - 2001:DB8:1::7
  - 2001:DB8:1::8