- name: Deploy MP-BGP IPv6 + VPNv4/VPNv6 configs
  hosts: all
  gather_facts: no

  tasks:
    - name: Render config
      template:
        src: ../templates/full_config.j2
        dest: ./configs/{{ inventory_hostname }}.cfg

    - name: Push config to device
      cisco.ios.ios_config:
        src: ./configs/{{ inventory_hostname }}.cfg
        save_when: modified
